insert $c20 isa american-maker has maker-name "AMC";
insert $c20 isa american-maker has maker-name "Cadillac";
insert $c20 isa american-maker has maker-name "Chrysler";
insert $c20 isa american-maker has maker-name "Chevrolet";
insert $c10 isa japanese-maker has maker-name "Datsun";
insert $c30 isa european-maker has maker-name "Ferrari";
insert $c30 isa european-maker has maker-name "Fiat";
insert $c20 isa american-maker has maker-name "Ford";
insert $c10 isa japanese-maker has maker-name "Honda";
insert $c30 isa european-maker has maker-name "Lotus";
insert $c30 isa european-maker has maker-name "Maserati";
insert $c10 isa japanese-maker has maker-name "Mazda";
insert $c30 isa european-maker has maker-name "Mercedes-Benz";
insert $c20 isa american-maker has maker-name "Pontiac";
insert $c30 isa european-maker has maker-name "Porsche";
insert $c10 isa japanese-maker has maker-name "Toyota";
insert $c30 isa european-maker has maker-name "Volvo";
match $m0 has maker-name "Mazda";
insert $c20 isa manual-car has model "Mazda RX4" has mpg 21.0 has cyl 6 has disp 160.0 has hp 110 has wt 2.62 has gear 4 has carb 4;
(made: $c20, maker: $m0) isa manufactured;
match $m0 has maker-name "Mazda";
insert $c20 isa manual-car has model "Mazda RX4 Wag" has mpg 21.0 has cyl 6 has disp 160.0 has hp 110 has wt 2.875 has gear 4 has carb 4;
(made: $c20, maker: $m0) isa manufactured;
match $m0 has maker-name "Datsun";
insert $c20 isa manual-car has model "Datsun 710" has mpg 22.8 has cyl 4 has disp 108.0 has hp 93 has wt 2.32 has gear 4 has carb 1;
(made: $c20, maker: $m0) isa manufactured;
match $m0 has maker-name "AMC";
insert $c10 isa automatic-car has model "Hornet 4 Drive" has mpg 21.4 has cyl 6 has disp 258.0 has hp 110 has wt 3.215 has gear 3 has carb 1;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "AMC";
insert $c10 isa automatic-car has model "Hornet Sportabout" has mpg 18.7 has cyl 8 has disp 360.0 has hp 175 has wt 3.44 has gear 3 has carb 2;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Chrysler";
insert $c10 isa automatic-car has model "Valiant" has mpg 18.1 has cyl 6 has disp 225.0 has hp 105 has wt 3.46 has gear 3 has carb 1;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Chrysler";
insert $c10 isa automatic-car has model "Duster 360" has mpg 14.3 has cyl 8 has disp 360.0 has hp 245 has wt 3.57 has gear 3 has carb 4;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Mercedes-Benz";
insert $c10 isa automatic-car has model "Merc 240D" has mpg 24.4 has cyl 4 has disp 146.7 has hp 62 has wt 3.19 has gear 4 has carb 2;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Mercedes-Benz";
insert $c10 isa automatic-car has model "Merc 230" has mpg 22.8 has cyl 4 has disp 140.8 has hp 95 has wt 3.15 has gear 4 has carb 2;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Mercedes-Benz";
insert $c10 isa automatic-car has model "Merc 280" has mpg 19.2 has cyl 6 has disp 167.6 has hp 123 has wt 3.44 has gear 4 has carb 4;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Mercedes-Benz";
insert $c10 isa automatic-car has model "Merc 280C" has mpg 17.8 has cyl 6 has disp 167.6 has hp 123 has wt 3.44 has gear 4 has carb 4;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Mercedes-Benz";
insert $c10 isa automatic-car has model "Merc 450SE" has mpg 16.4 has cyl 8 has disp 275.8 has hp 180 has wt 4.07 has gear 3 has carb 3;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Mercedes-Benz";
insert $c10 isa automatic-car has model "Merc 450SL" has mpg 17.3 has cyl 8 has disp 275.8 has hp 180 has wt 3.73 has gear 3 has carb 3;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Mercedes-Benz";
insert $c10 isa automatic-car has model "Merc 450SLC" has mpg 15.2 has cyl 8 has disp 275.8 has hp 180 has wt 3.78 has gear 3 has carb 3;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Cadillac";
insert $c10 isa automatic-car has model "Cadillac Fleetwood" has mpg 10.4 has cyl 8 has disp 472.0 has hp 205 has wt 5.25 has gear 3 has carb 4;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Ford";
insert $c10 isa automatic-car has model "Lincoln Continental" has mpg 10.4 has cyl 8 has disp 460.0 has hp 215 has wt 5.424 has gear 3 has carb 4;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Chrysler";
insert $c10 isa automatic-car has model "Chrysler Imperial" has mpg 14.7 has cyl 8 has disp 440.0 has hp 230 has wt 5.345 has gear 3 has carb 4;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Fiat";
insert $c20 isa manual-car has model "Fiat 128" has mpg 32.4 has cyl 4 has disp 78.7 has hp 66 has wt 2.2 has gear 4 has carb 1;
(made: $c20, maker: $m0) isa manufactured;
match $m0 has maker-name "Honda";
insert $c20 isa manual-car has model "Honda Civic" has mpg 30.4 has cyl 4 has disp 75.7 has hp 52 has wt 1.615 has gear 4 has carb 2;
(made: $c20, maker: $m0) isa manufactured;
match $m0 has maker-name "Toyota";
insert $c20 isa manual-car has model "Toyota Corolla" has mpg 33.9 has cyl 4 has disp 71.1 has hp 65 has wt 1.835 has gear 4 has carb 1;
(made: $c20, maker: $m0) isa manufactured;
match $m0 has maker-name "Toyota";
insert $c10 isa automatic-car has model "Toyota Corona" has mpg 21.5 has cyl 4 has disp 120.1 has hp 97 has wt 2.465 has gear 3 has carb 1;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Chrysler";
insert $c10 isa automatic-car has model "Dodge Challenger" has mpg 15.5 has cyl 8 has disp 318.0 has hp 150 has wt 3.52 has gear 3 has carb 2;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "AMC";
insert $c10 isa automatic-car has model "AMC Javelin" has mpg 15.2 has cyl 8 has disp 304.0 has hp 150 has wt 3.435 has gear 3 has carb 2;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Chevrolet";
insert $c10 isa automatic-car has model "Camaro Z28" has mpg 13.3 has cyl 8 has disp 350.0 has hp 245 has wt 3.84 has gear 3 has carb 4;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Pontiac";
insert $c10 isa automatic-car has model "Pontiac Firebird" has mpg 19.2 has cyl 8 has disp 400.0 has hp 175 has wt 3.845 has gear 3 has carb 2;
(made: $c10, maker: $m0) isa manufactured;
match $m0 has maker-name "Fiat";
insert $c20 isa manual-car has model "Fiat X1-9" has mpg 27.3 has cyl 4 has disp 79.0 has hp 66 has wt 1.935 has gear 4 has carb 1;
(made: $c20, maker: $m0) isa manufactured;
match $m0 has maker-name "Porsche";
insert $c20 isa manual-car has model "Porsche 914-2" has mpg 26.0 has cyl 4 has disp 120.3 has hp 91 has wt 2.14 has gear 5 has carb 2;
(made: $c20, maker: $m0) isa manufactured;
match $m0 has maker-name "Lotus";
insert $c20 isa manual-car has model "Lotus Europa" has mpg 30.4 has cyl 4 has disp 95.1 has hp 113 has wt 1.513 has gear 5 has carb 2;
(made: $c20, maker: $m0) isa manufactured;
match $m0 has maker-name "Ford";
insert $c20 isa manual-car has model "Ford Pantera L" has mpg 15.8 has cyl 8 has disp 351.0 has hp 264 has wt 3.17 has gear 5 has carb 4;
(made: $c20, maker: $m0) isa manufactured;
match $m0 has maker-name "Ferrari";
insert $c20 isa manual-car has model "Ferrari Dino" has mpg 19.7 has cyl 6 has disp 145.0 has hp 175 has wt 2.77 has gear 5 has carb 6;
(made: $c20, maker: $m0) isa manufactured;
match $m0 has maker-name "Maserati";
insert $c20 isa manual-car has model "Maserati Bora" has mpg 15.0 has cyl 8 has disp 301.0 has hp 335 has wt 3.57 has gear 5 has carb 8;
(made: $c20, maker: $m0) isa manufactured;
match $m0 has maker-name "Volvo";
insert $c20 isa manual-car has model "Volvo 142E" has mpg 21.4 has cyl 4 has disp 121.0 has hp 109 has wt 2.78 has gear 4 has carb 2;
(made: $c20, maker: $m0) isa manufactured;
