insert

# Entities

vehicle sub entity
	is-abstract;

car sub vehicle
	is-abstract

	has model
	has mpg
	has cyl
	has disp
	has hp
	has wt
	has gear
	has carb
	plays made;

automatic-car sub car;
manual-car sub car;

carmaker sub entity
	is-abstract
	has maker-name
	plays maker;

japanese-maker sub carmaker;
american-maker sub carmaker;
european-maker sub carmaker;

# Resources

model sub resource datatype string;
maker-name sub resource datatype string;
mpg sub resource datatype double;
cyl sub resource datatype long;
disp sub resource datatype double;
hp sub resource datatype long;
wt sub resource datatype double;
gear sub resource datatype long;
carb sub resource datatype long;

# Roles and Relations

manufactured sub relation
	relates maker
	relates made;

maker sub role;
made sub role;

# Reasoning
car
	has economical
	has powerful;
	
economical sub resource datatype string;
powerful sub resource datatype string;


$car-economy-true isa inference-rule
lhs
{$c isa car has mpg >= 19.0;}
rhs
{$c has economical "TRUE";};

$car-economy-false isa inference-rule
lhs
{$c isa car has mpg < 19.0;}
rhs
{$c has economical "FALSE";};

$car-powerful-true isa inference-rule
lhs
{$c isa car has hp >= 147;}
rhs
{$c has powerful "TRUE";};

$car-powerful-false isa inference-rule
lhs
{$c isa car has hp < 147;}
rhs
{$c has powerful "FALSE";};


