insert

# Entities

person sub entity
	plays parent
	plays child
	plays spouse1
	plays spouse2

	has identifier
	has firstname
	has surname
	has middlename
	has picture
	has age
	has birth-date
	has death-date
	has gender;

# Resources

identifier sub resource datatype string;
firstname sub resource datatype string;
surname sub resource datatype string;
middlename sub resource datatype string;
picture sub resource datatype string;
age sub resource datatype long;
birth-date sub resource datatype string;
death-date sub resource datatype string;
gender sub resource datatype string;

# Roles and Relations

marriage sub relation
	relates spouse1
	relates spouse2
	has picture;

spouse1 sub role;
spouse2 sub role;

parentship sub relation
	relates parent
	relates child;

parent sub role;
child sub role;	

# The following is added by the Grakn reasoner

person 
	plays wife
	plays husband
	plays granddaughter
	plays grandson
	plays father-in-law
	plays mother-in-law
	plays daughter-in-law
	plays son-in-law
	plays son
	plays daughter
	plays sibling1
	plays sibling2
	plays grandparent
	plays grandchild
	plays cousin1
	plays cousin2
	plays child-in-law
	plays parent-in-law
	plays mother
	plays father
	plays grandmother
	plays grandfather;

marriage sub relation
	relates husband
	relates wife;

husband sub role;
wife sub role;

parentship sub relation
	relates mother
	relates father
	relates son
	relates daughter;

mother sub parent;
father sub parent;
son sub child;
daughter sub child;

siblings sub relation
	relates sibling1
	relates sibling2;

sibling sub role is-abstract;
sibling1 sub sibling;
sibling2 sub sibling;

grandparentship sub relation
	relates grandparent
	relates grandfather
	relates grandmother
	relates grandchild
	relates granddaughter
	relates grandson;

grandparent sub role;
grandfather sub grandparent;
grandmother sub grandparent;
grandchild sub role;
grandson sub grandchild;
granddaughter sub grandchild;

cousins sub relation
	relates cousin1
	relates cousin2;

cousin sub role is-abstract;
cousin1 sub cousin;
cousin2 sub cousin;

in-laws sub relation
	relates child-in-law
	relates son-in-law
	relates daughter-in-law
	relates parent-in-law
	relates mother-in-law
	relates father-in-law;

child-in-law sub role;
son-in-law sub child-in-law;
daughter-in-law sub child-in-law;
parent-in-law sub role;
mother-in-law sub parent-in-law;
father-in-law sub parent-in-law;