insert

#############################################################################
#                                                                           #
#     			Rules to add genderized basic relations		   		        #
#                                                                           # 
#############################################################################

$genderizeMarriages isa inference-rule
lhs
{(spouse1: $s1, spouse2: $s2) isa marriage;
$s1 has gender "male";
}
rhs
{(husband: $s1, wife: $s2) isa marriage;};

$genderizeMarriages2 isa inference-rule
lhs
{(spouse1: $s1, spouse2: $s2) isa marriage;
$s1 has gender "female";
}
rhs
{(husband: $s2, wife: $s1) isa marriage;};


$genderizeParentships1 isa inference-rule
lhs
{(parent: $p, child: $c) isa parentship;
$p has gender "male";
$c has gender "male";
}
rhs
{(father: $p, son: $c) isa parentship;};

$genderizeParentships2 isa inference-rule
lhs
{(parent: $p, child: $c) isa parentship;
$p has gender "male";
$c has gender "female";
}
rhs
{(father: $p, daughter: $c) isa parentship;};

$genderizeParentships3 isa inference-rule
lhs
{(parent: $p, child: $c) isa parentship;
$p has gender "female";
$c has gender "male";
}
rhs
{(mother: $p, son: $c) isa parentship;};

$genderizeParentships4 isa inference-rule
lhs
{(parent: $p, child: $c) isa parentship;
$p has gender "female";
$c has gender "female";
}
rhs
{(mother: $p, daughter: $c) isa parentship;};


#############################################################################
#                                                                           #
#     				Rules to add inferred  relations		   		        #
#                                                                           # 
#############################################################################


$grandParents1 isa inference-rule
lhs
{($p, son: $gc) isa parentship;
(father: $gp, $p) isa parentship;
}
rhs
{(grandfather: $gp, grandson: $gc) isa grandparentship;};

$grandParents2 isa inference-rule
lhs
{($p, daughter: $gc) isa parentship;
(father: $gp, $p) isa parentship;
}
rhs
{(grandfather: $gp, granddaughter: $gc) isa grandparentship;};

$grandParents3 isa inference-rule
lhs
{($p, daughter: $gc) isa parentship;
(mother: $gp, $p) isa parentship;
}
rhs
{(grandmother: $gp, granddaughter: $gc) isa grandparentship;};

$grandParents4 isa inference-rule
lhs
{($p, son: $gc) isa parentship;
(mother: $gp, $p) isa parentship;
}
rhs
{(grandmother: $gp, grandson: $gc) isa grandparentship;};


$peopleWithSameParentsAreSiblings isa inference-rule
lhs
{(mother: $m, $x) isa parentship;
(mother: $m, $y) isa parentship;
(father: $f, $x) isa parentship;
(father: $f, $y) isa parentship;
$x != $y;
}
rhs
{(sibling1: $x, sibling2: $y) isa siblings;};

$peopleWithSiblingsParentsAreCousins isa inference-rule
lhs
{
(parent: $p, child: $c1) isa parentship;
($p, $p2) isa siblings;
(parent: $p2, child: $c2) isa parentship;
}
rhs
{(cousin1: $c1, cousin2: $c2) isa cousins;};

$inLaws1 isa inference-rule
lhs
{(husband: $x, wife: $y) isa marriage;
(mother: $il, $y) isa parentship;}
rhs
{(mother-in-law: $il, son-in-law: $x) isa in-laws;};

$inLaws2 isa inference-rule
lhs
{(husband: $x, wife: $y) isa marriage;
(father: $il, $y) isa parentship;}
rhs
{(father-in-law: $il, son-in-law: $x) isa in-laws;};

$inLaws3 isa inference-rule
lhs
{(husband: $x, wife: $y) isa marriage;
(father: $il, child: $y) isa parentship;}
rhs
{(father-in-law: $il, daughter-in-law: $y) isa in-laws;};

$inLaws4 isa inference-rule
lhs
{(husband: $x, wife: $y) isa marriage;
(mother: $il, child: $y) isa parentship;}
rhs
{(mother-in-law: $il, daughter-in-law: $y) isa in-laws;};
