insert

pet sub entity
    has name
    has sex
    has birth
    has death
    plays owned
    is-abstract;

cat sub pet;
dog sub pet;
snake sub pet;
hamster sub pet;
bird sub pet;

person sub entity
    has name
    has email
    plays owner;

owns sub relation
    relates owner
    relates owned;

owner sub role;
owned sub role;

email sub resource datatype string;
name sub resource datatype string;
sex sub resource datatype string;
birth sub resource datatype string;
death sub resource datatype string;

