insert

platform sub entity
	has platform-name
	plays supports;
	
platform-name sub resource datatype string;
supports sub role;
runs-on sub role;

genre sub entity
	has genre-name
	plays genre-of-game;
	
genre-name sub resource datatype string;
game-with-genre sub role;
genre-of-game sub role;

game sub entity
	has title
	has score
	has score-phrase
	has release-year
	plays game-with-genre
	plays runs-on;
	
title sub resource datatype string;
score sub resource datatype double;
score-phrase sub resource datatype string;
release-year sub resource datatype string;

compatibility sub relation
	relates supports
	relates runs-on;

has-genre sub relation
	relates game-with-genre
	relates genre-of-game;


